[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chebifier"
version = "1.3.0"
description = "An AI ensemble model for predicting chemical classes"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
authors = [
    {name = "Simon Flügel", email = "simon.fluegel@uni-osnabrueck.de"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
    "click",
    "pyyaml",
    "tqdm",
    "rdkit",
    "chebi-utils>=0.4",
    "lightgbm", # level-1 ensembles: learning to rank (ltr) and dynamic ensemble selection (des)
    "scikit-learn",
    "jsonargparse[signatures]==4.27.7",
]

[tool.setuptools]
packages = ["chebifier", "chebifier.ensemble", "chebifier.prediction_models"]

[tool.setuptools.package-data]
chebifier = ["*.yml"]

[project.optional-dependencies]
dev = ["black", "isort", "pre-commit"]

models = [
    "chebai_graph==1.2.1",
    "chebai==1.4.0",
    "chemlog-extra==1.1",  # includes ChemLog / Lopster
    "c3p"
]
