chemlog:
  type: chemlog
  model_weight: 100

my_gat_aug:
  type: gat
  ckpt_path: my_gat_aug.ckpt
  dataset_cls: chebai_graph.preprocessing.datasets.ChEBI25_WFGE_WGN_AsPerNodeType
  molecular_properties:
    - chebai_graph.preprocessing.properties.AtomNodeLevel
    - chebai_graph.preprocessing.properties.AugAtomAromaticity
    - chebai_graph.preprocessing.properties.AugAtomCharge
    - chebai_graph.preprocessing.properties.AugAtomHybridization
    - chebai_graph.preprocessing.properties.AugAtomNumHs
    - chebai_graph.preprocessing.properties.AugAtomType
    - chebai_graph.preprocessing.properties.AugNumAtomBonds
    - chebai_graph.preprocessing.properties.AtomFunctionalGroup
    - chebai_graph.preprocessing.properties.IsHydrogenBondDonorFG
    - chebai_graph.preprocessing.properties.IsHydrogenBondAcceptorFG
    - chebai_graph.preprocessing.properties.IsFGAlkyl
    - chebai_graph.preprocessing.properties.AugRDKit2DNormalized
    - chebai_graph.preprocessing.properties.BondLevel
    - chebai_graph.preprocessing.properties.AugBondAromaticity
    - chebai_graph.preprocessing.properties.AugBondInRing
    - chebai_graph.preprocessing.properties.AugBondType

my_gat:
  type: gat
  ckpt_path: my_gat.ckpt
  dataset_cls: chebai_graph.preprocessing.datasets.ChEBI25GraphProperties
  molecular_properties:
    - chebai_graph.preprocessing.properties.AtomType
    - chebai_graph.preprocessing.properties.NumAtomBonds
    - chebai_graph.preprocessing.properties.AtomCharge
    - chebai_graph.preprocessing.properties.AtomAromaticity
    - chebai_graph.preprocessing.properties.AtomHybridization
    - chebai_graph.preprocessing.properties.AtomNumHs
    - chebai_graph.preprocessing.properties.BondType
    - chebai_graph.preprocessing.properties.BondInRing
    - chebai_graph.preprocessing.properties.BondAromaticity
    - chebai_graph.preprocessing.properties.RDKit2DNormalized
